channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - pandas==2.2.3
  - matplotlib==3.9.2
  - plotly==5.18.0
  - seaborn==0.13.2
  - scikit-learn
  - mlflow==2.16
name: mlflow-env
